export const ROLES = {
  STUDENT: 'student',
  FACULTY: 'faculty',
  HOD: 'hod',
  ADMIN: 'admin',
};

export const PERMISSIONS = {
  // Study Materials
  MATERIAL_VIEW: 'material:view',
  MATERIAL_UPLOAD: 'material:upload',
  MATERIAL_EDIT: 'material:edit',
  MATERIAL_DELETE: 'material:delete',

  // Assignments
  ASSIGNMENT_VIEW: 'assignment:view',
  ASSIGNMENT_CREATE: 'assignment:create',
  ASSIGNMENT_SUBMIT: 'assignment:submit',
  ASSIGNMENT_GRADE: 'assignment:grade',

  // Attendance
  ATTENDANCE_VIEW_SELF: 'attendance:view_self',
  ATTENDANCE_VIEW_SECTION: 'attendance:view_section',
  ATTENDANCE_MARK: 'attendance:mark',

  // Timetable
  TIMETABLE_VIEW_SELF: 'timetable:view_self',
  TIMETABLE_VIEW_DEPT: 'timetable:view_dept',
  TIMETABLE_GENERATE: 'timetable:generate',

  // System & Admin
  USER_MANAGE: 'user:manage',
  DATA_IMPORT: 'data:import',
  SYSTEM_SETTINGS: 'system:settings',
  AUDIT_LOG_VIEW: 'audit:view',
};

export const ROLE_PERMISSIONS = {
  [ROLES.STUDENT]: [
    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.ASSIGNMENT_VIEW,
    PERMISSIONS.ASSIGNMENT_SUBMIT,
    PERMISSIONS.ATTENDANCE_VIEW_SELF,
    PERMISSIONS.TIMETABLE_VIEW_SELF,
  ],
  [ROLES.FACULTY]: [
    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.MATERIAL_UPLOAD,
    PERMISSIONS.MATERIAL_EDIT,
    PERMISSIONS.MATERIAL_DELETE,
    PERMISSIONS.ASSIGNMENT_VIEW,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.ATTENDANCE_VIEW_SELF,
    PERMISSIONS.ATTENDANCE_VIEW_SECTION,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.TIMETABLE_VIEW_SELF,
  ],
  [ROLES.HOD]: [
    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.MATERIAL_UPLOAD,
    PERMISSIONS.MATERIAL_EDIT,
    PERMISSIONS.MATERIAL_DELETE,
    PERMISSIONS.ASSIGNMENT_VIEW,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.ATTENDANCE_VIEW_SELF,
    PERMISSIONS.ATTENDANCE_VIEW_SECTION,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.TIMETABLE_VIEW_SELF,
    PERMISSIONS.TIMETABLE_VIEW_DEPT,
    PERMISSIONS.TIMETABLE_GENERATE,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.MATERIAL_UPLOAD,
    PERMISSIONS.MATERIAL_EDIT,
    PERMISSIONS.MATERIAL_DELETE,
    PERMISSIONS.ASSIGNMENT_VIEW,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_GRADE,
    PERMISSIONS.ATTENDANCE_VIEW_SELF,
    PERMISSIONS.ATTENDANCE_VIEW_SECTION,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.TIMETABLE_VIEW_SELF,
    PERMISSIONS.TIMETABLE_VIEW_DEPT,
    PERMISSIONS.TIMETABLE_GENERATE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.DATA_IMPORT,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],
};

export const hasPermission = (userRole, permission) => {
  if (!userRole) return false;
  const roleNorm = userRole.toLowerCase();
  const perms = ROLE_PERMISSIONS[roleNorm] || [];
  return perms.includes(permission);
};
